### ISSUE TITLE
[BP-528] Modal can't be closed

### ISSUE THREAD

**Issue by erwinromkes** [buckaroo-it/Magento2#51] opened 2020-10-14 13:38 UTC
After a new install of the module you get an model with _important information_, this modal can't be closed with the button **Done** With the ESC key the modal will be closed.

![Screenshot from 2020-10-14 15-33-42](https://user-images.githubusercontent.com/61180307/95996521-0d0cdd80-0e33-11eb-87d4-2a47ab330970.png)

**Environment**
PHP 7.3, Magento 2.4.0, Buckaroo 1.26 prelease.

**Comment by Buckaroo-Rens** [comment] 2020-10-15 13:54
@erwinromkes Thank you for the information. We cannot reproduce this at our own testing environment. Did you indeed do a complete new install or did you do a upgrade from a older version of our plugin?

**Comment by erwinromkes** [comment] 2020-10-16 06:27
It happen on a complete new Magento 2.4.0 installation with the 1.26 release.

**Comment by eshaudigital** [comment] 2020-10-19 04:39
Im facing the same issue.

I have upgraded magento version (2.2.9 > 2.4.0) and upgraded buckaroo payment (1.15.2 > 1.26.0) cant close the modal notification.
already asked buckaroo support, and the answer is to follow installation note : 

> IMPORTANT NOTE: if you update from v1.14.1 or lower to v1.15.2 then you need to take specific actions instead :
> 
> composer require buckaroo/magento2:1.15.2
> composer remove tig/buckaroo
> php bin/magento setup:upgrade
> 
> IMPORTANT NOTE: if you update from v1.14.1 or lower to v1.16.0 or higher then you need to take specific actions instead :
> 
> php bin/magento module:disable TIG_Buckaroo
> composer remove tig/buckaroo
> composer require buckaroo/magento2
> php bin/magento module:enable Buckaroo_Magento2
> php bin/magento setup:upgrade

but it still didn't solve my problem, even though i followed the advice.
and now I just got rid of it by hard coded the extension changing autoOpen option to false 
> vendor/buckaroo/magento2/view/adminhtml/ui_component/buckaroo_release_notification.xml
> around line 69
> <option name="autoOpen" xsi:type="boolean">false</option>

*this is not the proper way to fix, I just want to remove notification modal

**Comment by Buckaroo-Rens** [comment] 2020-10-19 08:55
Thank you @erwinromkes and @eshaudigital for the extra information. We will research this in our next sprint.

**Comment by Buckaroo-Rens** [comment] 2020-11-12 13:50
Changes are made to our code, will be released soon.

**Comment by Buckaroo-Rens** [comment] 2020-11-27 10:58
Published in latest release 1.28.0.

**Closed by Buckaroo-Rens** 2020-11-27 10:58 UTC
Labels: waiting for release
