### ISSUE TITLE
BP-3170 Redirect Process has no locking

### ISSUE THREAD

**Issue by boldhedgehog** [buckaroo-it/Magento2#856] opened 2023-11-21 09:16 UTC
**What**

The Redirect/Process controller and processor has no locking, while it should be locked per order, and this lock should be shared with the Push REST endpoint.

**Why**

Sometimes, when orders are paid in Buckaroo the Push callback and the process callback are performed at the same time, and this causes race condition concurrency issue and broken orders.

**How**

Place an order and pay in Buckaroo, get back to the success page. Buckaroo updates the order with buckaroo/push Rest endpoint and with a web request to buckaroo/redirect/process

**Expected result**

Order is invoiced, order items and totals are properly updated.

**Actual result**

- Invoice is created
- Order total paid and total due are not updated
- Order items qty_invoiced and row totals are not updated
- Redirect Process overwrites the order data in the DB that were was previously saved by the Push endpoint code

**Example log**

```
[2023-11-05T03:01:15.137202+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.1372|Buckaroo\Magento2\Model\Push::receivePush|1|array (
[2023-11-05T03:01:15.137356+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.1373|Buckaroo\Magento2\Model\Push::receivePush|1_2| [] []
[2023-11-05T03:01:15.137413+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.1374|Buckaroo\Magento2\Model\Push::lockPushProcessing|1| [] []
[2023-11-05T03:01:15.137611+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.1376|Buckaroo\Magento2\Model\Push::lockPushProcessing|5| [] []
[2023-11-05T03:01:15.137658+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.1377|Buckaroo\Magento2\Model\Push::receivePush|1_3| [] []
[2023-11-05T03:01:15.137700+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.1377|Buckaroo\Magento2\Model\Push::isGroupTransactionInfo|1| [] []
[2023-11-05T03:01:15.141540+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.1415|Buckaroo\Magento2\Model\Push::isPushNeeded|1| [] []
[2023-11-05T03:01:15.141675+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.1417|e0110f292c6066d00c321dbff83a1fe50b827b9c [] []
[2023-11-05T03:01:15.143438+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.1434|Buckaroo\Magento2\Model\Push::receivePush|1_5|'190' [] []
[2023-11-05T03:01:15.143514+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.1435|Buckaroo\Magento2\Model\Push::receivePush|1_10|'transaction_push' [] []
[2023-11-05T03:01:15.143574+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.1436|Buckaroo\Magento2\Model\Push::receivePush|1_20|NULL [] []
[2023-11-05T03:01:15.143619+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.1436|Buckaroo\Magento2\Model\Push::receivePushCheckDuplicates|1|'buckaroo_magento2_ideal' [] []
[2023-11-05T03:01:15.143860+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.1439|Buckaroo\Magento2\Model\Push::receivePushCheckDuplicates|5| [] []
[2023-11-05T03:01:15.143912+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.1439|Buckaroo\Magento2\Model\Push::receivePushCheckDuplicates|10|array (
[2023-11-05T03:01:15.143953+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.1439|Buckaroo\Magento2\Model\Push::receivePushCheckDuplicates|17| [] []
[2023-11-05T03:01:15.148326+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.1483|Buckaroo\Magento2\Model\Push::receivePushCheckDuplicates|20| [] []
[2023-11-05T03:01:15.148401+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.1484|Buckaroo\Magento2\Model\Push::receivePush|2|array (
[2023-11-05T03:01:15.148457+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.1485|Buckaroo\Magento2\Model\Push::canUpdateOrderStatus|1|array (
[2023-11-05T03:01:15.148501+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.1485|Buckaroo\Magento2\Model\Push::receivePush|3|true [] []
[2023-11-05T03:01:15.148541+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.1485|Buckaroo\Magento2\Model\Push::isGroupTransactionInfo|1| [] []
[2023-11-05T03:01:15.156119+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.1561|Buckaroo\Magento2\Model\Push::processPush|1|'BUCKAROO_MAGENTO2_STATUSCODE_SUCCESS' [] []
[2023-11-05T03:01:15.156234+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.1562|Buckaroo\Magento2\Model\Push::processPush|5|'processing' [] []
[2023-11-05T03:01:15.156282+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.1563|Buckaroo\Magento2\Model\Push::isPayPerEmailB2BModePushInitial|1| [] []
[2023-11-05T03:01:15.156376+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.1564|Buckaroo\Magento2\Model\Push::processSucceededPush|1|'processing' [] []
[2023-11-05T03:01:15.156428+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.1564|Buckaroo\Magento2\Model\Push::processSucceededPush|11| [] []
[2023-11-05T03:01:15.156489+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.1565|Buckaroo\Magento2\Model\Push::processSucceededPush|sendemail|'0' [] []
[2023-11-05T03:01:15.161215+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.1612|Buckaroo\Magento2\Model\Push::processSucceededPush|2| [] []
[2023-11-05T03:01:15.161343+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.1613|Buckaroo\Magento2\Model\Push::processSucceededPush|3| [] []
[2023-11-05T03:01:15.162597+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.1626|Buckaroo\Magento2\Model\Push::processSucceededPush|4| [] []
[2023-11-05T03:01:15.162664+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.1627|Buckaroo\Magento2\Model\Push::isPayPerEmailB2BModePushPaid|1| [] []
[2023-11-05T03:01:15.162709+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.1627|Buckaroo\Magento2\Model\Push::processSucceededPush|6| [] []
[2023-11-05T03:01:15.162750+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.1627|Buckaroo\Magento2\Model\Push::saveInvoice|1| [] []
[2023-11-05T03:01:15.166052+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.166|Buckaroo\Magento2\Model\Push::saveInvoice|5| [] []
[2023-11-05T03:01:15.166151+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.1661|Buckaroo\Magento2\Model\Push::saveInvoice|15| [] []
[2023-11-05T03:01:15.171253+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.1712|Buckaroo\Magento2\Observer\GroupTransactionRegister::execute|1| [] []
[2023-11-05T03:01:15.175317+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.1753|Buckaroo\Magento2\Observer\GroupTransactionRegister::execute|1| [] []
[2023-11-05T03:01:15.177420+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.1774|Buckaroo\Magento2\Observer\SendInvoiceMail::execute|1| [] []
[2023-11-05T03:01:15.184751+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.1847|Buckaroo\Magento2\Model\Push::saveInvoice|20| [] []
[2023-11-05T03:01:15.184943+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.1849|Buckaroo\Magento2\Model\Push::saveInvoice|25| [] []
[2023-11-05T03:01:15.450677+00:00] buckaroo_logging.DEBUG: 6547057b6e04e|1699153275.4506|Buckaroo\Magento2\Controller\Redirect\Process::execute|array (
[2023-11-05T03:01:15.464043+00:00] buckaroo_logging.DEBUG: 6547057b6e04e|1699153275.464|Buckaroo\Magento2\Controller\Redirect\Process::execute|2|791 [] []
[2023-11-05T03:01:15.464163+00:00] buckaroo_logging.DEBUG: 6547057b6e04e|1699153275.4642|Buckaroo\Magento2\Controller\Redirect\Process::execute|3|array (
[2023-11-05T03:01:15.466836+00:00] buckaroo_logging.DEBUG: 6547057b6e04e|1699153275.4668|Buckaroo\Magento2\Controller\Redirect\Process::execute|31| [] []
[2023-11-05T03:01:15.466912+00:00] buckaroo_logging.DEBUG: 6547057b6e04e|1699153275.4669|Buckaroo\Magento2\Controller\Redirect\Process::execute|33| [] []
[2023-11-05T03:01:15.466991+00:00] buckaroo_logging.DEBUG: 6547057b6e04e|1699153275.467|Buckaroo\Magento2\Controller\Redirect\Process::execute|34|'pending_payment' [] []
[2023-11-05T03:01:15.497538+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.4975|Buckaroo\Magento2\Model\Push::saveInvoice|30|sendinvoiceemail [] []
[2023-11-05T03:01:15.539658+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.5396|Buckaroo\Magento2\Model\Push::saveInvoice|35| [] []
[2023-11-05T03:01:15.550835+00:00] buckaroo_logging.DEBUG: 6547057b6e04e|1699153275.5508|Buckaroo\Magento2\Controller\Redirect\Process::execute|5| [] []
[2023-11-05T03:01:15.550915+00:00] buckaroo_logging.DEBUG: 6547057b6e04e|1699153275.5509|Buckaroo\Magento2\Controller\Redirect\Process::handleProcessedResponse|15| [] []
[2023-11-05T03:01:15.573009+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.573|Buckaroo\Magento2\Model\Push::processSucceededPush|8| [] []
[2023-11-05T03:01:15.573301+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.5733|Buckaroo\Magento2\Model\Push::updateOrderStatus|0|array (
[2023-11-05T03:01:15.573362+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.5734|Buckaroo\Magento2\Model\Push::updateOrderStatus|1| [] []
[2023-11-05T03:01:15.573404+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.5734|||| $orderState: |1|processing [] []
[2023-11-05T03:01:15.576317+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.5763|Buckaroo\Magento2\Model\Push::processSucceededPush|9| [] []
[2023-11-05T03:01:15.576571+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.5766|Buckaroo\Magento2\Model\Push::receivePush|5| [] []
[2023-11-05T03:01:15.576628+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.5766|Buckaroo\Magento2\Model\Push::unlockPushProcessing|1| [] []
[2023-11-05T03:01:15.578083+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.5781|Buckaroo\Magento2\Model\Push::unlockPushProcessing|5| [] []
[2023-11-05T03:01:15.578153+00:00] buckaroo_logging.DEBUG: 6547057b217cd|1699153275.5781|Buckaroo\Magento2\Model\Push::receivePush|6| [] []
```

This line proves that the order was saved while the Push was still in progress:
```
[2023-11-05T03:01:15.466991+00:00] buckaroo_logging.DEBUG: 6547057b6e04e|1699153275.467|Buckaroo\Magento2\Controller\Redirect\Process::execute|34|'pending_payment' [] []
```

**Comment by boldhedgehog** [comment] 2023-11-21 09:22
This is were the Push processing locked:

https://github.com/buckaroo-it/Magento2/blob/master/Model/Push.php#L229

There is no locking in here https://github.com/buckaroo-it/Magento2/blob/master/Controller/Redirect/Process.php#L268

Also, in addition to an external locking, OrderMutex class can be used to safely update Orders:

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sales/Model/OrderMutexInterface.php#L13

Example can be found here, in this code an Order is invoiced too:

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sales/Model/InvoiceOrder.php#L144

```php
public function execute(
        $orderId,
        $capture = false,
        array $items = [],
        $notify = false,
        $appendComment = false,
        InvoiceCommentCreationInterface $comment = null,
        InvoiceCreationArgumentsInterface $arguments = null
    ) {
        return $this->orderMutex->execute(
            (int) $orderId,
            \Closure::fromCallable([$this, 'createInvoice']),
            [
                $orderId,
                $capture,
                $items,
                $notify,
                $appendComment,
                $comment,
                $arguments
            ]
        );
    }
```

**Comment by Buckaroo-Rene** [comment] 2023-11-21 09:55
@boldhedgehog,

Thank you for taking the time to provide such detailed information.
We appreciate your effort in outlining the issue you have found.
I'm glad to inform you that we've created an internal ticket to thoroughly investigate and address this matter.
Our team will prioritize this issue and start with the research from our side straight away.
We'll keep you updated on the progress and any developments regarding this issue.

**Comment by Buckaroo-Rene** [comment] 2023-11-24 09:29
@boldhedgehog we've did some additional research on this issue.
But we don't don't think that the locking system will solve the issue.
Because we are not only interested in the concurrent requests we are interested also in the order of the requests.
Redirects should be executed before Push.

**This is why for some methods we use skip_push:**
![skip_push](https://github.com/buckaroo-it/Magento2/assets/105488705/adcfc4c7-058a-4f22-b9e1-8df2acd179d2)

### **1. We can not use Order Mutex because Order Mutex make a lock at the row database level on sales_order table and we affect more tables than sales_order.**
 
           sales_order_payment
           sales_order
 
### **2. Locking system it will fix just a part of the problem, only concurent request, but we are also interested to execute the Redirect before the Push.**
<br>

### **1. Regarding the Use of Order Mutex:**
We've determined that utilizing Order Mutex is not feasible for our current needs. The primary reason is that Order Mutex implements a row-level lock specifically on the sales_order table in the database. However, our operations extend beyond just the sales_order table, significantly affecting other tables such as sales_order_payment. Due to this, the locking mechanism provided by Order Mutex, while effective for singular table transactions, doesn't encompass the broader scope of our database interactions.

### **2. Limitations of the Locking System:**
While implementing a locking system might address issues related to concurrent requests, it's important to note that this solution only partially addresses our overall challenge. Our main objective also includes ensuring that the Redirect operation is executed prior to the Push. Therefore, simply resolving the concurrency issue with a locking system does not fully align with our operational requirements. We need a more comprehensive solution that not only manages concurrent requests but also adheres to the specific sequence of operations we require, especially prioritizing the Redirect before the Push.


### **We are currently researching other options to solve the issue that you are facing.**

@boldhedgehog One additional question regarding the Buckaroo plugin configuration.
In the **Advanced Configuration** we have a setting about the order confirmation e-mail which can be send in sync mode.
Do you have that enabled or disabled?

**_Example:_**
![sync-mode](https://github.com/buckaroo-it/Magento2/assets/105488705/3cafde25-26bc-43e8-ab31-2d1cd1241dd6)



_CC: @harli91 @LucianTuriacArnia @Buckaroo-Rens_

**Comment by boldhedgehog** [comment] 2023-11-24 09:52
Good morning, @Buckaroo-Rene ,

Thank you for your detailed reply. The concurrency issue with PSPs exists since Magento 1, and I understand the complexity of the solution. I hope you will find the best approach for this. We usually ended up with a scheduled task that looked for broken orders and fixed the numbers in the DB.

As for the email settings, in our case they are "Yes" for Send order confirmation email and "No" for the sync mode.

Best regards.

**Comment by Buckaroo-Rene** [comment] 2023-11-28 14:54
Good afternoon @boldhedgehog ,

Thank you for your reply. Hereby a update regarding our process so far.
The issue is still under development. We have chosen to use Magento's LockManagerInterface because it allows merchants to have control over which lock provider to use, with the default being the database.
Currently, the first version has been developed, and we are now in the testing phase to validate the solution.
After the solution is validated, we will create the final version and then proceed to more thorough testing.
If we need to give a rough estimation, then we think that we need 2-4 more days to finalize the development (without the final testing).

Best Regards,
René

**Comment by Buckaroo-Rene** [comment] 2023-12-08 10:22
Hi @boldhedgehog ,

Hereby a new update from our side:
We've been testing our fix and this is currently still in progress, but the results are looking good so far.
Hopefully we can finalize them by the end of today so we can share a commit with you next week so you can check if this is a proper solution for you. Eventually we will also include it in a full release but that will need more testing time.

Best Regards,
René

**Comment by boldhedgehog** [comment] 2023-12-08 10:27
Thank you for the update, René.

**Comment by Buckaroo-Rene** [comment] 2023-12-11 15:33
@boldhedgehog ,

Hereby a new update from our side.
At the moment, all tests are still passing smoothly. We're currently focusing on rigorously testing the most recent changes to ensure they are accurately reflected in the database. That's the last part we need to test and we will need a few additional hours to conduct these tests thoroughly.
Hopefully, by tomorrow, I'll be able to share the commit with you. Feel free then to test it on your end as well if you'd like.

Best Regards,
René

**Comment by Buckaroo-Rene** [comment] 2023-12-12 16:02
@boldhedgehog ,

Hereby a new update. We a solution for the issue.
Perhaps you will be able to apply the commit to a staging to see if this is a solution for the issue you are facing.
https://github.com/buckaroo-it/Magento2/pull/859

We will be preparing a new Magento 2 release, but this will take some more time to test.
Since we are finalizing some other tickets and testing the new version in general with all the changes in multiple Magento 2 versions.

We would appreciate some feedback on the commit and we're hoping this solves the issue on your end.

Best Regards,
René

**Comment by boldhedgehog** [comment] 2024-01-12 13:07
Good afternoon, @Buckaroo-Rene ,

Thank you for the update, and please excuse me for the late reply.

I checked the changes, but it's hard for me to "run" the code in my mind.

Is there a way for us to install a version of this package with fix and test on non-Production environment? Or we better wait for the release? What would you suggest?

**Comment by Buckaroo-Rene** [comment] 2024-01-31 15:22
@boldhedgehog ,

Sorry missed this one, but we are preparing a new release v1.47.0 which is currently being tested by our QA,
This still takes some time unfortunately since we need to test multiple versions of Magento and the release will include alot of changes.

**Comment by Buckaroo-Rene** [comment] 2024-03-19 08:04
@boldhedgehog ,
You've might already spotted it, but this has been released in [v1.47.0.](https://github.com/buckaroo-it/Magento2/releases/tag/v1.47.0).

**Closed by Buckaroo-Rene** 2024-03-19 08:04 UTC
Labels: Bug, Status: Waiting for info, Status: Waiting for release, Refactor, Priority: Normal, 👏Thank You✨

**Comment by boldhedgehog** [comment] 2024-05-06 13:33
@Buckaroo-Rene I'd like to let you know, that the release with this fix was working on Production for some time already without issues.

**Comment by Buckaroo-Rene** [comment] 2024-05-06 14:08
Hi @boldhedgehog,

Thank you very much for the confimation.
