### ISSUE TITLE
BP-3465 Creditcard is grouped config not working correctly

### ISSUE THREAD

**Issue by bke1999** [buckaroo-it/Magento2#941] opened 2024-03-14 09:43 UTC
https://github.com/buckaroo-it/Magento2/blob/6a84ec89db1842c894cb1251888d42cafaa13eee/view/frontend/web/js/view/payment/method-renderer/creditcard.js#L172
The script currently checks for strict equality but since the config returns string '1' the result is always false. As a work around we changed comparison to non strict but you may want to change value return from the config.
Magento 2.4.6-p4. Module Version 1.47.0

**Comment by jemico** [comment] 2024-03-18 16:23
I can confirm that this option is not working correctly.

@bke1999 can you explain me more how i can use your workarround?

**Comment by Buckaroo-Rens** [comment] 2024-03-18 18:34
Thanks both @bke1999 and @jemico for notifying us. We will look into this a.s.a.p.

**Comment by SandervdHulst** [comment] 2024-03-18 19:19
Thank you @bke1999 and @jemico. This is a known issue and the fix will be added to our next release. We have created a Pull Request for this issue: [BP-3465 creditcards are not displayed in grouped](https://github.com/buckaroo-it/Magento2/pull/939).

**Comment by jemico** [comment] 2024-03-18 21:02
@SandervdHulst added the fix and it is working! Thanks

**Comment by Buckaroo-Rene** [comment] 2024-03-19 08:02
@jemico ,

Good to hear and thank you for confirming this so quickly.

**Comment by Buckaroo-Rene** [comment] 2024-04-29 09:39
Issue closed because this has been released in:
[v1.48.0](https://github.com/buckaroo-it/Magento2/releases/tag/v1.48.0)

**Closed by Buckaroo-Rene** 2024-04-29 09:39 UTC
Labels: Bug, Status: Released, 👏Thank You✨
