### ISSUE TITLE
BP-3761 Incorrect calculation of Grand Total Excluding Tax in JS (related to: BP-3564)

### ISSUE THREAD

**Issue by Ahmet-Djedovic** [buckaroo-it/Magento2#978] opened 2024-05-04 16:00 UTC
Issue Overview:
The current implementation of the getGrandTotalExclTax function in the module is flawed.
view/frontend/web/js/view/checkout/summary/grand-total.js

It calculates the grand total excluding tax using a manual subtraction of the tax amount from the grand total.
This method is prone to errors and may not always produce accurate results.

Proposed Solution:
Utilize the simplified and more reliable implementation of the getGrandTotalExclTax function from Magento 2 default.
This implementation directly returns the grand total from the 'total' object, ensuring accurate calculations without the need for manual adjustments.

Proposed Changes:
- Replace the existing getGrandTotalExclTax function in the module with the simplified implementation from Magento 2 default.

**Comment by Buckaroo-Rene** [comment] 2024-05-06 09:44
@Ahmet-Djedovic ,

Thank you for logging this issue. We'll take a look at with the team.

Regards,
René

**Comment by Buckaroo-Rene** [comment] 2024-09-17 13:33
This is released in version [1.50.0](https://github.com/buckaroo-it/Magento2/releases/tag/v1.50.0) of the Buckaroo Plugin.

**Comment by JSeverein** [comment] 2024-10-03 19:40
@Buckaroo-Rene 
Is it possible this issue still persists in 1.50.1? We can still reproduce it after updating. 

It seems the view/frontend/web/js/view/checkout/summary/grand-total.js file was removed and later re-added.
And the substraction of tax amount is still there:
https://github.com/buckaroo-it/Magento2/blob/v1.50.1/view/frontend/web/js/view/checkout/summary/grand-total.js#L74

**Comment by Buckaroo-Rene** [comment] 2024-10-09 13:44
@JSeverein thanks for contacting us.
We found indeed another issue and are looking into it.
I've reopened the ticket and we'll keep you posted.

**Comment by Buckaroo-Rene** [comment] 2024-10-11 07:56
@JSeverein ,
Hereby a new update. We found a solution to resolve this issue and it is currently being tested.
Hopefully we can do a hotfix release early next week for it.

**Comment by Buckaroo-Rene** [comment] 2024-12-02 13:55
Closed this ticket since a fix was implemented in [v1.50.0](https://github.com/buckaroo-it/Magento2/releases/tag/v1.50.0).

**Closed by Buckaroo-Rene** 2024-12-02 13:55 UTC
Labels: Status: Released, Priority: Normal, 👏Thank You✨
