### ISSUE TITLE
Orders are set to PROCESSING too soon in 1.43.0 causing problems in the order flow

### ISSUE THREAD

**Issue by CyberSecutor** [buckaroo-it/Magento2#599] opened 2022-10-21 09:30 UTC
In this commit:
https://github.com/buckaroo-it/Magento2/commit/113a62faf2c6147f0a08f3e76874e60bb20a4854

Orders are set to processing as soon as a transaction is started.
This is the wrong flow for Magento. They should only be set to processing when the payment is successful.

Now when someone aborts an iDeal payment for example, the order is kept on processing for a while and other systems will assume it is payed for. 
This can cause invoices to be send early and even items to be shipped without a payment.

See the Order flow diagram of the Magento docs.
https://docs.magento.com/user-guide/sales/order-status-workflow.html

Unfortunatly we had to revert to 1.42.0 again to make sure there are no unpayed orders being shipped.

**Comment by Buckaroo-Rens** [comment] 2022-10-21 09:59
@CyberSecutor We are looking into it right now

**Comment by MaxiAxi-Jorn** [comment] 2022-10-21 10:06
Tried to reproduce this, since I was testing 1.43.0 as well, but I can't reproduce this. Not with iDeal in test mode or live mode.

**Comment by Buckaroo-Rens** [comment] 2022-10-21 10:07
@CyberSecutor With 'abort an iDEAL payment' do you mean: 

- Clicking the go back button
- CLicking the cancel button on the bank page 

At this moment we cannot reproduce this.

**Comment by Buckaroo-Rens** [comment] 2022-10-21 10:56
We found a edge-case scenario were this was reproducable. We made a fix and will get 1.43 offline. Commit can be found here: https://github.com/buckaroo-it/Magento2/pull/600/commits/dfa2fa9b57d44c1907793f599d00b1ce05000b96 advise could also be to downgrade to 1.42.0 

New version of our plugin will be released early next week.

**Comment by CyberSecutor** [comment] 2022-10-23 13:38
Hi @Buckaroo-Rens, 

one of the methods is to start an iDeal payment, and not finish it at all. (i.e. just close the browser tab on the bank page).
But that is just them most noticable scenario, since the time between transaction start and finish is quite long.

**Comment by Buckaroo-Rens** [comment] 2022-10-25 10:50
Fixed in 1.43.1

**Closed by Buckaroo-Rens** 2022-10-25 10:50 UTC
Labels: Released
