### ISSUE TITLE
SOAP Violation of encoding rules

### ISSUE THREAD

**Issue by fazed** [buckaroo-it/Magento2#9] opened 2020-02-10 09:59 UTC
Hi,

We're experiencing issues when trying to pay for an order in the checkout (last step). After investigating the error log, we found the following message:
`[2020-02-10 09:33:00] main.CRITICAL: SOAP-ERROR: Encoding: Violation of encoding rules {"exception":"[object] (SoapFault(code: 0): SOAP-ERROR: Encoding: Violation of encoding rules at xxxx/vendor/buckaroo/magento2/Soap/Client/SoapClientWSSEC.php:33)"} []`

Previously the payments worked just fine, but since we've upgraded Magento from 2.3.3 to 2.3.4 this issue started to appear. Currently we have the latest Buckaroo module version installed (1.17.0). We also confirmed whether the settings in the admin have the correct values. The store is running in test mode.

Any help is appreciated, this issue is currently blocking our Magento upgrades.

**Comment by saranchuk-hys** [comment] 2020-02-10 10:40
Hello @fazed !
Thanks for your request!

Could you please specify:
- did you use Magento Open Source 2.3.4 ?
- which php version use ?
- which payment method was selected ?

**Comment by Sil-B** [comment] 2020-02-10 13:18
@saranchuk-hys  We have the same issue after upgrading to 

- Magento open Source 2.3.4
- 7.2.xxx
- any payment method.

**Comment by fazed** [comment] 2020-02-10 13:45
Hi @saranchuk-hys, thanks for the fast response.

We're using:
- Magento 2.3.4 CE
- PHP 7.3.x
- Any payment method

**Comment by Buckaroo-Rens** [comment] 2020-02-11 09:15
@Sil-B @fazed We are currently unable to reproduce this issue on our own testing environment. Could you please give us some additional information? What checkout extension are you using etc. Thank you in advance.

**Comment by Sil-B** [comment] 2020-02-11 09:51
@Buckaroo-Rens Thanks for the quick reply. For this project we are using the Amasty One Step Checkout :(. I did not try it with the native checkout.

**Comment by Buckaroo-Rens** [comment] 2020-02-11 09:52
@Sil-B Could you please test with native checkout? We do not support the Amasty One Step Checkout currently.

**Comment by Sil-B** [comment] 2020-02-11 13:23
@Buckaroo-Rens I've tested it with native checkout and default lume theme. Same issue: 

`[2020-02-11 13:21:13] main.CRITICAL: SOAP-ERROR: Encoding: string '6\xe9...' is not a valid utf-8 string {"exception":"[object] (SoapFault(code: 0): SOAP-ERROR: Encoding: string '6\\xe9...' is not a valid utf-8 string at /home/xxx/magento2/vendor/buckaroo/magento2/Soap/Client/SoapClientWSSEC.php:33)"} []`

**Comment by fazed** [comment] 2020-02-12 14:48
@Sil-B, we've managed to fix our issue by flushing the WSDL cache. Apparently when upgrading PHP from < 7.3 to >= 7.3, the cached WSDL files are borked.

**Comment by Buckaroo-Rens** [comment] 2020-02-17 12:49
Issue of @Sil-B was fixed by filling in the Buckaroo credentials again. Issue closed.

**Closed by Buckaroo-Rens** 2020-02-17 12:49 UTC
