### ISSUE TITLE
[BP-1302] Page redirects to the empty shopping cart after clicking 'Back' browser button

### ISSUE THREAD

**Issue by Tetiana123Q** [buckaroo-it/Magento2#470] opened 2022-01-25 09:03 UTC
**Steps to reproduce:**
1. Add product to the cart
2. Proceed to checkout
3. Chose 'Credit card' payment method, for example Visa
4. Click  place an order on your webshop
5. When you are on Buckaroo page for entering card information, click Back button in your browser
6. Pay attention that the page redirects to the empty shopping cart

**Actual result:** Page redirects to the empty shopping cart after clicking 'Back' browser button
**Expected result:** Page redirects to the shipping checkout step without losing filled information after clicking 'Back' browser button on Buckaroo side
**Additional info:**
* We updated Buckaroo from 1.35 to 1.39. 
* tested on Windows 11, Google Chrome 97 (but I think it is common for all browsers)

**Comment by Buckaroo-Rens** [comment] 2022-01-25 10:27
@Tetiana123Q Thanks for the information. Can you clarify do you/did you use SecondChance in version 1.35? If yes, do you now use our separate plugin for this?

**Comment by Tetiana123Q** [comment] 2022-01-26 09:59
> @Tetiana123Q Thanks for the information. Can you clarify do you/did you use SecondChance in version 1.35? If yes, do you now use our separate plugin for this?

As I can see, we have SecondChance functionality only within frames of buckaroo/magento2 (if we talk about buckaroo modules). No separate module.

**Comment by Buckaroo-Rens** [comment] 2022-02-01 11:26
That's strange since Second Chance was introduced in removed in 1.39.0 and if your not using the Second Chance module itself then you should not have any left-overs.

**Comment by Tetiana123Q** [comment] 2022-02-01 14:03
> That's strange since Second Chance was introduced in removed in 1.39.0 and if your not using the Second Chance module itself then you should not have any left-overs.

That was misunderstanding indeed. We checked in old version. In version 1.39 we do not have Second Chance module and do not have classes related with second chance.

**Comment by Buckaroo-Rens** [comment] 2022-02-15 12:04
@Tetiana123Q We did some additional testing last week and our QA came back to me with the following info: 

> Issue cannot be reproduced. Tested on M23 and m24, Firefox and Chrome, Loggedin and Guest orders. Please note that Windows 10 was used.

Since it's not reproducible i would like to advice you to contact our support team via support@buckaroo.nl you can refer to this specific issue. To help you via support we need additional info, video, logs or access to your staging environment. 

I'm closing this ticket.

**Closed by Buckaroo-Rens** 2022-02-15 12:04 UTC
Labels: no action needed
