### ISSUE TITLE
[BP-1879] Afterpay rejection message is not clear when consumers use a not identical country for billing/shipping addresses.

### ISSUE THREAD

**Issue by SvitlanaZakrevska** [buckaroo-it/Magento2#518] opened 2022-07-03 14:42 UTC
Hello!

We're experiencing an issue with AfterPay payment method - getting error instead of successfully placed order.

**Steps to reproduce:**
1. Add some product to the cart
2. Go to the first checkout step -> add shipping address (NL address)
3. Go to the second checkout step
4. Chose AfterPay payment method -> add some billing address (this one should be BE address)
5. Fill all other required fields/checkboxes
6. Press button in order to place an order
7. Pay attention to the error in the top of the page

If both addresses are from the Netherlands, order is placed successfully.

**Errors:**
![Screenshot from 2022-07-03 16-16-23](https://user-images.githubusercontent.com/74734841/177044493-d6fd5626-8c53-4a39-b154-85bb1ace91f0.png)
![07 1609309q01s$s](https://user-images.githubusercontent.com/74734841/177044571-7281ae3c-8e96-49c8-bba2-79fc9e6504e0.png)

Magento version (enterprise edition): 2.4.3-p2
Buckaroo version: v1.39.0

**Comment by Buckaroo-Rene** [comment] 2022-07-04 08:25
Good morning @SvitlanaZakrevska ,

Thank you for your message. Due to a restriction from Afterpay it is not allowed to place a order with Afterpay with different countries for the billing and shipping addresses.
We are showing their rejection message in the checkout which is not very clear to be honest (Pay rejected. The following errors occurred: ()_).
I will create a ticket for our team to see If we can make this error message from Afterpay more clear for consumers.

Can you perhaps share the Buckaroo transaction key for your attempt?
Then I can add your example to our internal ticket as well.

**Comment by SvitlanaZakrevska** [comment] 2022-07-04 12:47
@Buckaroo-Rene, I suppose I can share the transaction key, where in DB I can find it?

**Comment by Buckaroo-Rene** [comment] 2022-07-05 07:37
Hi @SvitlanaZakrevska,

That would be great. There are 2 ways to find the transaction key:

(1.) If you have a timestamp of the transaction attempt, then you can look it up in the Buckaroo Plaza -> Transactions -> Overview. Click on the transaction attempt of that time, and then you'll see the transaction key displayed in the main transaction information.

(2.) You can look up the transaction attempt in the Magento backend. Inn the order notes there should be a transaction key visible. Here you also need to know when the transaction was placed (around what time/day).

**Comment by Buckaroo-Rene** [comment] 2022-07-07 07:38
@SvitlanaZakrevska,

Thanks for checking it anyway. I've managed to reproduce the message, so it is not mandatory to have another example anymore. The ticket for our development team is currently on our backlog and it needs to be scheduled in a sprint.

**Comment by Buckaroo-Rene** [comment] 2023-05-09 11:58
**Pull Request:**
https://github.com/buckaroo-it/Magento2/pull/714

**Comment by Buckaroo-Rene** [comment] 2023-10-02 11:21
Released in [v1.46.0](https://github.com/buckaroo-it/Magento2/releases/tag/v1.46.0).

**Closed by Buckaroo-Rene** 2023-10-02 11:21 UTC
Labels: Status: Released, Priority: Minor
