### ISSUE TITLE
Quote with 100% discount still returns unavailable payment methods

### ISSUE THREAD

**Issue by stefanfr** [buckaroo-it/Magento2#270] opened 2021-06-15 09:35 UTC
Hi There,

Just testing the latest version of the module when I found out that when you apply a coupon code with 100% discount, resulting in a 0 value order the activated payment methods within Buckaroo are still showing in the checkout. However when selecting one of them results in a 400 error with the message:
```The requested payment method is not available```

There is an option to set the min order value, this wil disable the method when below set value. But a zero order value should always mean the payment method is nog available since placing such order results in an error

**Comment by vladislav-padalka-hys** [comment] 2021-06-15 10:37
Hi @stefanfr !

First of all : thanks a lot for your request !

But it's quite strange, because we've quickly checked zero amount checkout and saw no Buckaroo payment methods activated  in such case.
It's actual for the latest version 1.36.1 , as well as one of previous (1.35.0)
Please check below screenshots :

https://drive.google.com/file/d/14FoxsjZd3i-1QAPuBrehsCpie9Lp9j7z/view?usp=sharing
https://drive.google.com/file/d/1jELPKxDeMZPyBa_yTi1uiTlfD_HxxmWc/view?usp=sharing

Only one payment method is shown as you can see there and it's Magento's default one (Zero Subtotal Checkout) which is  exactly for such cases.
Maybe we've missed something and you can clarify conditions / settings when it happens or, if it's convenient for you, share URL where we can see this.
Meanwhile, we will try to reproduce this with our QA engineers. 

Thank you in advance !

**Comment by stefanfr** [comment] 2021-06-15 11:14
Hi @vladislav-padalka-hys,

I'm sorry if forgot to mention that we have a headless checkout and are using the API to collect the payment methods. Within the response the Buckaroo methods are persent and no attribute states it should be disabled. 

When i check this in the Magento checkout itself the request also returns those methods. Are those methods hidden via the frontend or should they also be disabled within the api response?

Sidenote: When setting a min order value of 0.01 within the admin, the api doesn't return the Buckaroo method.

Thanks you for looking in to this.

**Comment by vladislav-padalka-hys** [comment] 2021-06-15 12:09
@stefanfr looks like we are able to reproduce the issue : it's enough to disable Magento's "Zero Subtotal Checkout" method and in such case by default methods will be visible if total is 0 
we will schedule a fix for this and let you know when it will be available 
thanks again !

**Comment by vladislav-padalka-hys** [comment] 2021-06-23 11:50
Good afternoon @stefanfr !

We've made a fix and it will be available in upcoming release soon!

**Comment by Buckaroo-Rens** [comment] 2021-08-18 07:22
Released in 1.37

**Closed by Buckaroo-Rens** 2021-08-18 07:22 UTC
Labels: Released
